### ISSUE TITLE
Automatic suspension from smart detection not working

### ISSUE THREAD

**Issue by ajwsert** [sebsoftnl/moodle-tool_usersuspension#6] opened 2023-06-12 14:40 UTC
I don't know where to report it then sorry in advance, also I don't know if it's something at my end but recently the automatic suspension based on smart detection stopped working.
I checked the logs and it shows the task ran successfully but the users are still active and in "Users to Suspend" they are shown with negative time in "Suspend in".
Either Moodle and the plug-in are up-to-date (Moodle build 20230512, plugin v4.0.1 [build 2022090102]) and it worked a while back. When I realized it I had users pending to be suspended for like 2 weeks.
Let me know if I need to provide more info.

**Comment by elearningdifferently** [comment] 2024-09-10 21:39
I have a same issue with plugin v4.0.1

v3.5.9 was working fine

**Comment by rogiervandongen** [comment] 2024-09-23 10:03
Will be fixed in new version (released this week)

**Closed as completed by rogiervandongen** 2024-09-23 10:03 UTC

**Comment by elearningdifferently** [comment] 2024-09-29 22:09
Upgraded to version 4.0.2 (build 2024090100) (2024090100) - but seems the problem is still present there. Any hints on where to look to fix this? :)

**Comment by rogiervandongen** [comment] 2024-10-07 08:20
@elearningdifferently 
For some reason my changes were dropped or discarded and never actually got pushed.
The way it was (is) solved, is that we mark a "lastrun" for every task when completed. With another change this no longer worked as intended and was always set in advance. This meant the task never actually ran it's basic code.

I've fixed the deletion task as well (or maybe I should say I "re-did" the code), so you can either wait for the new version to land on Moodle.org or just install a new version from this repository when it lands here (it will be version 4.0.4 (build 2024092301))
